### ISSUE TITLE
Heap-buffer-overflow

### ISSUE THREAD

**Issue by sergio-nsk** [Nikssssss/Labs#2]
https://github.com/Nikssssss/Labs/blob/bc53c5f46017fdc9652c8c27db00c34305fd9109/lab6/lab6.c#L14

В 15 тесте размер данных 0 байт. Обращение `a[0]` к массиву в выделенной памяти размером 0 байт приводит к падению программы.

**Comment by mrnikitagusev** [comment]
Исправил
